# Site settings
name: Ontology Tools
group: SPOT Team
email: noreply@ebi.ac.uk
domain: /
baseurl: /
permalink: pretty

# Add custom CSS / JS here
custom_css:
 - "static/simple_layout.css"
# - "{{site.baseurl}}/static/css/ANOTHER-CSS-COMPONENTS.css"
# custom_js:
# - "{{site.baseurl}}/static/js/YOUR-CSS-COMPONENTS.js"
# - "{{site.baseurl}}/static/js/ANOTHER-CSS-COMPONENTS.js"
ga_code: 'UA-XXXXX-X'

# Build settings
markdown: kramdown
